### ISSUE TITLE
Use Preconfigured AWS NAT Instance

### ISSUE THREAD

**Issue by RichardKnop** [alphagov/cf-terraform#116]
Is there a reason to use Ubuntu and configure it via a setup script?

Wouldn't it be easier and simpler to just use instance provided by AWS? E.g. `ami-69ae8259`.

And just change the user to `ec2-user` instead of `ubuntu`. No need to run a provisioner script.

**Comment by jimconner** [comment]
Hi Richard - I think the logic behind that decision was so that we could use the same provisioning steps regardless of which IaaS provider we were deploying to. Right now we're only deploying to AWS though as the feature set of other IaaS providers doesn't give us the same level of convenience. I should also mention that we're not actively developing the cf-terraform stuff anymore - you'll find all of our work for the last 6 months in paas-cf instead.

**Comment by RichardKnop** [comment]
@jimconner Thanks Jim. I might look at the work you have done as I am doing something similar.

**Comment by dcarley** [comment]
Hey, Richard. Hope you're well.

@jimconner's right. It was essentially carried this over from alphagov/tsuru-terraform#80. We also lacked some confidence about keeping the AWS provided AMI up-to-date. Nowadays I'd recommend using the managed NAT gateway devices if you're only using AWS, as we have done in paas-cf: alphagov/paas-cf#56
